[package]
name = "raytracing-improved"
version = "0.1.0"
edition = "2021"

[features]
miri = []
aabbx4 = []

[dependencies]
sti = { git = "https://github.com/leddoo/sti" }
sdl2 = "*"
image = "*"
rayon = "*"

[profile.release]
debug = 2
