[package]
name = "raytracing-improved"
version = "0.1.0"
edition = "2021"

[features]
miri = []
aabbx4 = []

[dependencies]
sti = { git = "https://github.com/leddoo/sti", rev = "f5a03ee7" }
sdl2 = "0.37.0"
image = "0.25.4"
rayon = "1.8.1"

[profile.release]
debug = 2
